Add GitHub Gists partial functionality (by using Octokit)
ivanrod-gh/test-guru pull request #15
Opened 2023-03-08 16:54 UTC by ivanrod-gh

2023-03-08 17:17 UTC, BubuntuClu requested changes

2023-03-08 17:17 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  def gist
давай более REST'овый подход использовать. ты тут создаешь гист. это по сути `create` экшен. сделай контроллер для гистов и реализуйм там этот метод

2023-03-08 17:17 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    @client.last_response.status == REST_API_STATUS_CREATED
не стоит выносить логику из сервиса. у тебя сервис предоставляет интерфейс `success?`, а как он реализован в клиенте, уже дело не контроллера. надо логику проверки успеха перенести в сервис/клиент

2023-03-08 17:17 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    @client = Octokit::Client.new('access_token': ENV['GITHUB_GIST_ACCESS_TOKEN'])
зачем тебе именно инстанс перменная? почему обычная не подходит?
дальшейшие операции с ней не выглядит супер очевидно

2023-03-08 17:19 UTC, BubuntuClu requested changes

2023-03-08 17:19 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    current_user.access_level == 'Admin' if current_user
зачем поменял? ты вынес логику определения то пользователь админ в контроллер. а зачем контроллеру это уметь? за это сама модель должна отвечать. так как пользователь должен уметь знать админ он или нет

2023-03-09 07:10 UTC, BubuntuClu requested changes

2023-03-09 07:10 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    end
проверка на 201 выглядела лучше чем это, что лежит в `@response` не понятно и вызвав `@response.success?` ты не можешь гарантировать что запрос прошел успешно. ты вообще можешь вызвать любой метод у этого объекта и ты не получишь никакой ошибки

2023-03-09 07:10 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +    @response = github_gist
ты же тут не ответ получаешь, а объект своего сервиса, нейминг путает.
разбей получение сервиса и вызов создания гиста через сервис в два действия, не суй все в один метод

2023-03-09 13:59 UTC, ivanrod-gh commented on app/services/gist_question_service.rb
> +    end
Метод сервиса @response.success? - это ответ сервиса контроллеру и большего контроллеру не надо. В зависимости от используемого клиента, этот метод вызывает или success? для экземпляра Faraday::Response, проверяя "успешность", или id? для экземпляра Sawyer::Resource, проверяя, выдан ли гисту идентификатор в системе. Метод id? можно поменять на что-то там, но не на проверку статуса - у Sawyer::Resource нет такого метода или поля. У клиента - есть.
В данный момент у ответа сервиса, который возвращается контроллеру на вызов метода .post, доступны два метода - .success?, проверяющий успешность сохранения гиста на удаленный сервер, и .gist_url, возвращающий адрес гиста. Никакие другие методы контроллером использоваться не должны - это должно отражаться в документации, но я такого задания не вижу. В данной концепции сервис для контроллера работает как интерфейс между контроллером и чем-то-там, что связано с GitHub, и как оно там связано - контроллер волновать не должно. Ответы фарадея и сойера невозможно использовать контроллером - у этих ответов разные методы и разные форматы данных.
Метод сервиса .success? вполне адекватно оценивает факт сохранения гиста в БД GitHub.
Любое false срабатывание success?, которое означает, что гист не был сохранен в БД GitHub, приводит к тому, что гист не сохраняется и в локальную БД с выводом соответствующего флеша пользователю.
Если success? true, то гист сохраняется в локальную БД.
В коде были закольцованы редиректы, это я исправил.
Любое исключение (в том числе - вызывание несуществующих методов у @response) будет перехвачено rescue с информированием пользователя об ошибке при сохранении гиста. Как я вижу, клиенты выкатывают исключения даже на отсутствие соединения, на неверные данные тела гиста и т.д. - это не должно класть приложение.
Никакого логирования таких ошибок не ведется - такой задачи не было.

2023-03-09 15:33 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    self
зачем этот костыль, если это можно решить через присваивание инстанса сервиса в отдельную переменную в контроллере?

2023-03-09 15:33 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    byebug
это положит приложение

2023-03-09 15:33 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    end
>Если success? true, то гист сохраняется в локальную БД.

я к тому что ты не можешь гарантировать что там придет и как строится эта проверка. сделай свою проверку успеха того как отработал сервис. для этого есть метод `last_response` у октокита.

>у Sawyer::Resource нет такого метода или поля. У клиента - есть.

вот как раз про это. что у тебя клиент октокита, и у этого клиента надо проверить его последний запрос

2023-03-10 10:54 UTC, merged