Lesson17
ivanrod-gh/test-guru pull request #18
Opened 2023-03-31 17:50 UTC by ivanrod-gh

To production

2023-04-01 18:22 UTC, BubuntuClu commented on app/mailers/feedbacks_mailer.rb
> +    mail to: User.first.email
лучше не первого пользователя брать, а первого админа

2023-04-01 18:22 UTC, BubuntuClu commented on app/views/feedbacks/create.html.erb
> +<div class="row justify-content-center">
вьюхи для метода `create` не должно существовать(вьюхи есть для `get` методов). ты при создании перенаправляешь на какую-то страницу с каким-то сообщением. либо на вьюху создания фидбэка с текстом ошибки, либо куда-то еще с темкстом что сообщение ушло

2023-04-03 16:57 UTC, BubuntuClu requested changes

2023-04-03 16:57 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    test.questions.empty? ? TEST_EMPTY_PERCENT : ((correct_questions / test.questions.count.to_f) * 100).to_i
на мой взгляд, это странное решение. оно может ввести пользователя в замешательство. я начал тест и ничего не отвечая провалил его.

подумай над другим подходом

2023-04-04 08:39 UTC, BubuntuClu commented on db/migrate/20230404010714_add_passable_to_tests.rb
> +    add_column :tests, :passable?, :boolean, default: false
в БД не добавляем лишние символы в наименование столбцов. только буквы

2023-04-04 08:39 UTC, BubuntuClu commented on app/models/test.rb
> +  QUESTIONS_MIN_COUNT = 1
эти ограничения могут меняться постоянно, задолбаешься их отслеживать. поступи проще, чтобы ничего не считать, переложи ответственность за публикацию тестов на самого автора теста. он сам знает когда тест готов. он знает сколько хочет вопросов и сколько ответов к ним.

как доп валидацию можно(в рамках курса можно не делать) сделать проверку что у каждого вопроса должен быть правильный ответ, но это именно доп проверка при публикации теста, а не как основная

2023-04-04 08:39 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @tests = Test.all.where(passable?: true)
`Test.passable`/`Test.published` или какой-то другой синоним к тестам, которые можно проходить. сделай через скоуп

2023-04-04 08:39 UTC, BubuntuClu commented on app/controllers/feedbacks_controller.rb
> +  def status; end
зачем этот метод? почему сразу на рут не редиректить?

2023-04-04 14:11 UTC, ivanrod-gh commented on app/controllers/feedbacks_controller.rb
> +  def status; end
при переходу на рут для незарегистрированного пользователя автоматически будет показан alert с необходимостью логина без показа notice про успешную отправку письма

2023-04-04 18:18 UTC, ivanrod-gh commented on app/models/test.rb
> +  QUESTIONS_MIN_COUNT = 1
Оставил минимальные ограничения для тестов, автопроверку убрал, для авторов сделал ручную публикацию с проверкой на минимальные требования. Для редактирования вопросов/ответов теста теперь надо тест снять с публикации

2023-04-04 18:23 UTC, merged