Add badges to project
ivanrod-gh/test-guru pull request #19
Opened 2023-04-11 16:14 UTC by ivanrod-gh

2023-04-11 18:18 UTC, BubuntuClu requested changes

2023-04-11 18:18 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +    when 1..2
при увеличении разных типов баджей этот код будет разрастаться? это плохое решение. стоит подумать как сделать так чтобы избежать доработак таких

2023-04-11 18:18 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      Badge.all.each { |badge| badge.calculate_achievement(@test_passage) }
вынеси это в сервис наград. не размещай прямую логику работы с баджами просто в коде контроллера

2023-04-11 18:18 UTC, BubuntuClu commented on app/models/badge.rb
> +class Badge < ApplicationRecord
по-хорошему, модель должна хранить в себе правила валидации, скоупы, ассоциации. всю остальную бизнес-лоигку стоит выносить в другие объекты.

весь код по награждению перемести в сервис наград. пусть он этим занимается, а не сам бадж

2023-04-11 18:18 UTC, BubuntuClu commented on app/models/badge.rb
> +    passages = TestPassage.where("user_id = ? AND test_id = ?", test_passage.user.id, data_test_id)
в `where` условии используй методы AR чтобы передавать параметры для фильтрации. если ты пишешь там чистый sql то стоит писать его используя `Arel`

2023-04-11 18:18 UTC, BubuntuClu commented on app/models/badge.rb
> +      test_passage.user.received_achievements.push(self)
этот код дублируется во всех методах проверки, надо убрать дублирование кода

2023-04-11 18:18 UTC, BubuntuClu commented on app/models/badge.rb
> +    return unless test_passage.test.category.id == data_category_id.to_i && Category
почему так много проверок в коде?
первая понятная, проверка атрибута, а вторые третьи зачем?
ты получаешь по сути два массива айдишников, которые надо сравнить, и они либо равны и тогда выдаешь нагруда, либо нет и тогда не выдаешь. каокй-то сложный код написан сейчас

2023-04-11 18:18 UTC, BubuntuClu commented on app/models/badge.rb
> +    success_count = TestPassage.joins_test_by_category_id(data_category_id.to_i)
зачем тут группировка?
находишь все тесты категории. и этиже тесты ищешь среди униклаьных успешных прохождений пользователей

2023-04-11 18:18 UTC, BubuntuClu commented on app/models/badge.rb
> +                               .where("test_passages.user_id = ? and successful = true", test_passage.user.id)
тут тоже перепиши на рубишный манер. фильтрацию про успех, можно вынести в скоуп, используешь это не раз в коде

2023-04-11 18:18 UTC, BubuntuClu commented on app/models/badge.rb
> +  CHECK_METHODS = {
константы по стайл гайду идут то методов

2023-04-11 18:18 UTC, BubuntuClu commented on db/migrate/20230405080138_create_badge_achievements.rb
> +    add_index :badge_achievements, [:user_id, :badge_id]
создай индекс в рамках создания таблицы, чтобы за один запрос создавалась она, нет смысла выносить эту операцию отдельно

2023-04-12 11:52 UTC, ivanrod-gh commented on app/models/badge.rb
> +  CHECK_METHODS = {
так оно и было, но это не работает - сначала надо объявить метод, а уже потом на него ссылаться

2023-04-12 19:01 UTC, ivanrod-gh commented on app/models/badge.rb
> +    passages = TestPassage.where("user_id = ? AND test_id = ?", test_passage.user.id, data_test_id)
Это который модуль Arel? Его использование не разбиралось в скринкастах, там вариант выше подавался как достаточный для защиты от инъекций. Здесь [https://api.rubyonrails.org/classes/Arel.html](url) сказано, что Arel небезопасен при работе с атрибутами модели

2023-04-13 06:30 UTC, BubuntuClu commented on app/models/badge.rb
> +  CHECK_METHODS = {
не понял коммента. сначала описываешь константы, а потмо методы где они используются.
почему это не работает?

2023-04-13 06:36 UTC, BubuntuClu requested changes

2023-04-13 06:36 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      BadgeAchievementService.new(@test_passage).calculate_achievements
для соблюдения единства вызова сервисов, метод который запускает логику это `call`, остальные методы приватные и можешь их называть по своему усмотрению

2023-04-13 06:36 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    return unless @test_passage.successful
зачем инициализировать объект сервиса и тратить на него время и память, если потом ты сразу можешь из него выйти? сделай проверку перед вызовом сервиса

2023-04-13 06:36 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +      @requirement_id = badge.requirement_id
старайся использовать явные параметры, а не инстанс переменные. с явными парамтеарми легче отследить логику того, что передается

2023-04-13 06:36 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    return unless passages.count == 1
последней строкой метода может быть просто `passage.count == 1`?

2023-04-13 06:36 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    return unless @test_passage.complete_percent == BadgeRequirement::PASSED_PERCENT[:COMPLETELY]
последней строкой метода может быть просто `@test_passage.complete_percent == BadgeRequirement::PASSED_PERCENT[:COMPLETELY]`?

2023-04-13 06:36 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    return unless (Test.where(category_id: @requirement_data.to_i) - success_tests).empty?
тут тоже самое

2023-04-13 06:36 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    return unless Category.find_by(id: @requirement_data).present? && @test_passage
переделай все проверки на `if`, какой смысл в доп инвертации значения для читающего и для тебя самого?

2023-04-13 06:36 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    return unless (tests_remaining.count.to_f / Test.count) * 100 <= pass_percent - @requirement_data.to_i
и тут

2023-04-13 06:36 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    return unless CHECK_METHODS[@requirement_id][:reference].bind(self).call
кажется что вложенность `reference` лишняя. просто номер правила и метод для него выглядит достаточным для решения

2023-04-13 12:29 UTC, ivanrod-gh commented on app/models/badge.rb
> +  CHECK_METHODS = {
если константа находится в начале класса, то вот на этом месте `1 => { reference: instance_method(:check_requirement_first_pass) }` интерпретатор ищет метод `check_requirement_first_pass`, не находит его и выдает ошибку NoMethod

2023-04-13 13:20 UTC, ivanrod-gh commented on app/services/badge_achievement_service.rb
> +    return unless Category.find_by(id: @requirement_data).present? && @test_passage
это желания рубокопа, я сам unless использую редко и только тогда, когда подходит по смыслу типа next unless

2023-04-13 16:30 UTC, BubuntuClu approved these changes

2023-04-13 16:30 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    if Test.find_by(id: @badge.requirement_data).present? && @test_passage.test.id == @badge
в блок не стоит оборачивать просто ` if .. != ...` вметсо `unless ==`

2023-04-14 12:51 UTC, merged