Add seeds initial data. Add 2 methods to models
ivanrod-gh/test-guru pull request #5
Opened 2023-01-17 16:30 UTC by ivanrod-gh

2023-01-17 17:11 UTC, BubuntuClu requested changes

2023-01-17 17:11 UTC, BubuntuClu commented on app/models/test.rb
> +    category = Category.find_by(title: category_title)
ты знаком с операцией `join`, надо ее использовать тут, чтобы за один запрос получить нужные данные

2023-01-17 17:11 UTC, BubuntuClu commented on app/models/test.rb
> +    Test.where(category_id: category.id).select(:title).order(title: :desc).map(&:title)
`map(&:title)` можно заменить на `pluck(:title)`

2023-01-17 17:11 UTC, BubuntuClu commented on db/migrate/20230110151110_create_tests.rb
> +      t.integer :level, null: false, default: 1
нельзя править файлы миграции задним числом. твои правки не будут применены у других разработчиков, работающие с этим же приложением. все изменения в миграциях надо убрать, которые ты внес и через новые миграции внести нужные правки

2023-01-17 17:11 UTC, BubuntuClu commented on db/migrate/20230110152620_create_users.rb
> +      t.string :tests
как должно работать это поле? почему тут стринг и что в этой стринге будет храниться?

2023-01-17 17:11 UTC, BubuntuClu commented on app/models/user.rb
> +    return nil if tests.nil? || Test.find_by(level: test_level).nil?
`tests.nil?` - что такое `tests`? откуда береться?

2023-01-17 17:11 UTC, BubuntuClu commented on app/models/user.rb
> +    return nil if tests.nil? || Test.find_by(level: test_level).nil?
а, я понял, это как раз то поле у пользователя. не, это неправильный вариант

2023-01-17 17:11 UTC, BubuntuClu commented on app/models/user.rb
> +    tests.split('/').each { |test| user_test_ids.push test.split('=')[0].to_i }
надо реализовать связь многие-ко-многим между тестами и пользователями. и на этой связи делать нужный запрос. 

`user_test_ids.push test.split('=')[0].to_i` -> `user_test_ids.push(test.split('=')[0].to_i)` - всегда ставь скобки вокруг аргументов метода

2023-01-18 10:04 UTC, ivanrod-gh commented on app/models/test.rb
> +    category = Category.find_by(title: category_title)
Не понял, при чем тут join. Сам сам запрос здесь: Test.where(category_id: Category.find_by(title: category_title).id).select(:title).order(title: :desc).pluck(:title)
Строки выше - для пресечения исключения и чтобы два раза не писать одно и то же

2023-01-18 11:33 UTC, ivanrod-gh commented on app/models/test.rb
> +    category = Category.find_by(title: category_title)
Вообще - это вопрос валидации. Вероятно - уберу, пока тема с валидациями не будет пройдена

2023-01-19 06:40 UTC, BubuntuClu commented on app/models/test.rb
> +    category = Category.find_by(title: category_title)
ты делаешь первый запрос на ` Category.find_by(title: category_title).id`, получаешь ID и потом этот ID подставляешь в запрос `Test.where(category_id:`. используя `join` ты за один запрос получаешь нужные данные

2023-01-19 06:43 UTC, BubuntuClu requested changes

2023-01-19 06:43 UTC, BubuntuClu commented on app/models/test.rb
> +    Category.find_by(title: category_title).tests.select(:title).order(title: :desc).pluck(:title)
выполни этот метод в консоли, ты увидишь какие запросы у тебя выполняются.
надо сделать запрос относительно таблицы тестов с лжойном категорий, чтобы по названию категории отфильтровать все тесты

2023-01-19 06:43 UTC, BubuntuClu commented on db/migrate/20230118102555_add_answer_explanation_to_questions.rb
> +    add_column :questions, :answer_explanation, :string
что планируется в этом столбце хранить?

2023-01-19 06:43 UTC, BubuntuClu commented on db/migrate/20230118185235_create_users_tests.rb
> +      t.belongs_to :user
нужно добавить внешний ключ

2023-01-19 06:43 UTC, BubuntuClu commented on db/migrate/20230118185235_create_users_tests.rb
> +      t.belongs_to :test
нужно добавить внешний ключ

2023-01-19 06:43 UTC, BubuntuClu commented on db/migrate/20230118185235_create_users_tests.rb
> +    create_table :users_tests, id: false do |t|
убирать столбец `id` не рекомендую, тебе может потребоваться в будущем обращаться к данным этой таблицы и тогда тебе надо будет руками создавать этот столбец и заполнять его.

2023-01-19 06:45 UTC, BubuntuClu commented on app/models/test.rb
> +    Category.find_by(title: category_title).tests.select(:title).order(title: :desc).pluck(:title)
первый запрос: `Category.find_by(title: category_title)`
второй запрос: к результату первого применяется ассоциация `tests`

и кстати тут можно получить ошибку, если такой категории не найдется, то к `nil` будет применен метод `tests` что вызовет ошибку

2023-01-19 12:03 UTC, ivanrod-gh commented on db/migrate/20230118102555_add_answer_explanation_to_questions.rb
> +    add_column :questions, :answer_explanation, :string
Пояснения, почему правильный ответ - правильный, если в тесте реализован функционал подсказок или же по завершению описывается, что было выбрано правильно, а что - нет. Т.к. правильных ответов может быть несколько, то хранится в вопросе. Пояснений в тесте также может и не быть. Что именно там хранится можно увидеть в seeds.rb для теста по заголовку Викторина: Животные

2023-01-19 12:11 UTC, ivanrod-gh commented on db/migrate/20230118185235_create_users_tests.rb
> +    create_table :users_tests, id: false do |t|
Мануал по рельсам рекомендует его убирать из-за нестабильного поведения. Хорошо, посмотрим, что получится

2023-01-19 17:30 UTC, merged