Add routes for tests and questions. Add Test and Question controllers…
ivanrod-gh/test-guru pull request #8
Opened 2023-01-30 15:59 UTC by ivanrod-gh

…. Add basic views for Test and Question

2023-01-30 18:07 UTC, BubuntuClu requested changes

2023-01-30 18:07 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = Question.create!(params.permit(:body, :test_id))
1 - обработку параметров стоит вынести в отдельный метод, так как он тебе еще пригодиться
2 - тест передавать не надо параметром, надо создавать вопрос через ассоциацию от теста, тогда параметр подставится автоматически
3 - не надо использовать бэнг метод, чтобы схватить ошибку. тебе надо проверить успешно ли будет сохранен объект в БД, чтобы пользователю дать внятный ответ
типа того что сделно строкой ниже, только не через велосепед, а посредствам рельсы и ее инструментов

2023-01-30 18:07 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render plain: question.id.nil? ? question.errors.inspect : "Вопрос успешно создан"
ты не сможешь получить в ответ список ошибок, так как твой метод создания вопросы выше выкинет эксепшн если что-то заполнено не правильно

2023-01-30 18:07 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question.destroy!
это тоже не должен быть бэнг метод. их используют в исключительных случаях, в блоках по транзакциям. твой случай не такой

2023-01-30 18:07 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
добавь опцию `shallow: true` для ресурса вопросов, посомтри как изменятся роуты и адаптируй код в контроллере под эти изменения

2023-01-31 16:29 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = @test.questions.create(question_params)
по стандартному флоу надо заменить `create`на `new/build`, а в строке ниже проверять `if question.save` - этот оператор возвращает `true/false`

2023-01-31 16:29 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form action="/tests/1/questions" method="post">
было правильно, сейчас нет. динамически параметр надо подставлять. верни код

2023-01-31 17:21 UTC, ivanrod-gh commented on app/views/questions/new.html.erb
> +<form action="/tests/1/questions" method="post">
Потом уже заметил. Вставлю @test.id

2023-01-31 17:32 UTC, merged