Add basic questions views
ivanrod-gh/test-guru pull request #9
Opened 2023-02-03 19:45 UTC by ivanrod-gh

2023-02-04 16:33 UTC, BubuntuClu requested changes

2023-02-04 16:33 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :create_question_or_test, only: %i[new]
тебе не нужен колбэк на один экшен. просто в экшене напиши нужный код.
колбэки не очень хорошая практика(в контроллерах еще более менее норм для поиск аобъектов, а вот в моделях лучше их стараться почти не писать)

2023-02-04 16:33 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def create_question_or_test
чет нейминг у тебя получился не соотвертсующий действию в методе. ты инициализируешь объект вопроса для теста, а не создаешь вопрос или тест

2023-02-04 16:33 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author.to_s}/#{repo.to_s}"
добавь сюда использование хэлпера `link_to`. сейчас метод просто вставляет строки в строку. это выглядит странно, их же можно сразу на странице было бы написать

2023-02-04 16:33 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header(prefix, question)
передавай сюда только объект вопроса. по состоянию вопроса `persisted?/new_record?` определяй какой заголовок писать

2023-02-04 16:33 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h2><%= question_header('Редактировать текст вопроса', @question) %></h2>
размещая этот код во вьюхе `edit/new` ты лишаешь смысла хэлпер. его задача в том, чтобы неважно где его вызывают он показывает правильный нейминг.

по сути у тебя в `edit/new` вьюхах должна быть только одна строка `<%= render 'form' %>`. все остальное одинаковое и выносится в форму

2023-02-04 16:33 UTC, BubuntuClu commented on app/views/questions/_form.html.erb
> +<%= form_with model: model_data, local: true do |form| %>
модель дата для обоих вьюх у тебя будет `[@test, @question]`, рельса по наличию объектов сама построит правильный путь

2023-02-04 16:33 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def index; end
этот экшн тебе уже не нужен

2023-02-07 05:23 UTC, VidgarVii requested changes

2023-02-07 05:23 UTC, VidgarVii commented on app/assets/stylesheets/application.css
> +}
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-02-07 05:23 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = find_question
find_question уже определяет инстанс переменную @question
данная строчка кода будет лишней

2023-02-07 05:23 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>      question = Question.find(params[:id])
есть колебек find_question который можно использовать в этом экшене. И данный код будет не нужен

2023-02-07 05:23 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    if question.persisted?
в данном случаи если по каким-то причинам вопрос не сможет удалиться, то это показатель на не верные объявления ассоциаций в моделях.Что указывает на баг. Пользователь не должен и не сможет решать подобные случаи.
По этому можно убрать все эти проверки

2023-02-07 05:23 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_tests, only: %i[index]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2023-02-07 05:23 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    Time.zone.now.year
так тоже можно
Еще вариант не много сократить код
`Time.current.year`

2023-02-07 05:23 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    link_to description, "https://github.com#{url_path}"
ссылки на внешние ресурсы правильно открывать в новой закладке
Делается, что бы не потерять юзера на сайте. И для удобства

2023-02-07 05:23 UTC, VidgarVii commented on app/views/questions/_button_back.html.erb
> +<%= button_to 'Вернуться', test_questions_path(@question.test), method: :get %>
чтобы не плодить целые формы, уместно и логичней использовать ссылки для гет и пост запросов

2023-02-07 05:23 UTC, VidgarVii commented on app/views/questions/_button_delete.html.erb
> +<%= button_to "Удалить", question_path(instance), method: :delete, data: { confirm: 'Вы уверены?'}, style: "color: red" %>
No new lina at end of file
не должно быть во всём коде

2023-02-07 05:23 UTC, VidgarVii commented on app/views/questions/_question.html.erb
> +  <div class="TableStyle">
принято использовать lowercase
https://google.github.io/styleguide/htmlcssguide.html#Capitalization

2023-02-07 05:23 UTC, VidgarVii commented on app/views/questions/index.html.erb
> +<div align="center">
по ТЗ список вопросов должен быть на странице конкретного теста. Получается этот файл не нужен.
Так же не вижу в реквесте исправление роутов и страницы самого теста

2023-02-07 15:12 UTC, ivanrod-gh commented on app/views/questions/_button_back.html.erb
> +<%= button_to 'Вернуться', test_questions_path(@question.test), method: :get %>
Все кнопки вынесены во фрагменты для использования в разных местах. Это позволяет их править в одном месте, а не искать по всему коду.
button_to ничем не хуже link_to

2023-02-08 16:49 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    find_question
почему ты сам вызываешь метод, а не добавляешь в колбэк вызов для этого экшена?

просто должна быть какая-то система у тебя. либо ты не используешь колбэки и сам дергаешь методы, либо используешь колбэки и тогда сам не вызываешь методы. сейчас у тебя и так, и так. стоит определиться и в одном стиле писать

2023-02-08 18:55 UTC, merged